apiVersion: v2
name: redis-replication
version: 0.3.0
description: Redis Replication with Sentinel
keywords:
  - redis-operator
  - redis
  - kubernetes
sources:
  - https://github.com/OT-CONTAINER-KIT/redis-operator
  - https://github.com/OT-CONTAINER-KIT/redis-operator/tree/main/charts/redis-operator
maintainers:
  - name: alexlebens
icon: https://github.com/OT-CONTAINER-KIT/redis-operator/raw/main/static/redis-operator-logo.svg
appVersion: v0.21.0
