# -- Override the name of the resources
replicationNameOverride: ""

# -- Override the namespace of the chart
namespaceOverride: ""

# -- Password
existingSecret:
  enabled: false
  name: secret-name
  key: password

# -- Add additional labels
additionalLabels: {}

# -- Redis Replication settings
redisReplication:
  clusterSize: 3

  # -- Security
  podSecurityContext:
    fsGroup: 1000
    runAsUser: 1000

  # -- Image
  image:
    repository: quay.io/opstree/redis
    tag: v8.4.0
    pullPolicy: IfNotPresent

  # -- Resources
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

  # -- Storage
  volumeClaimTemplate:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: ceph-block

  # -- Metrics
  redisExporter:
    enabled: true
    image:
      repository: quay.io/opstree/redis-exporter
      tag: v1.80.1
    serviceMonitor:
      enabled: true
      interval: 30s
      scrapeTimeout: 10s
      extraLabels: {}

  # -- Redis Sentinel settings
  sentinel:
    enabled: false
    size: 3

    # -- Image
    image:
      repository: quay.io/opstree/redis-sentinel
      tag: v8.4.0
      pullPolicy: IfNotPresent

    # -- Resources
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
