apiVersion: v2
name: postgres-cluster
version: 7.6.0
description: Cloudnative-pg Cluster
keywords:
  - database
  - postgres
sources:
  - https://github.com/cloudnative-pg/cloudnative-pg
  - https://github.com/cloudnative-pg/charts/tree/main/charts/cluster
maintainers:
  - name: alexlebens
icon: https://avatars.githubusercontent.com/u/100373852?s=48&v=4
# renovate: datasource=github-releases depName=cloudnative-pg/cloudnative-pg
appVersion: v1.28.1
