apiVersion: v2
name: cloudflared
version: 2.2.0
description: Cloudflared Tunnel
keywords:
  - cloudflare
  - tunnel
sources:
  - https://github.com/cloudflare/cloudflared
  - https://github.com/bjw-s-labs/helm-charts/tree/main/charts/library/common
maintainers:
  - name: alexlebens
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 4.6.2
icon: https://avatars.githubusercontent.com/u/314135?s=48&v=4
appVersion: "2025.11.1"
