apiVersion: v2
name: generic-device-plugin
version: 0.20.0
description: Generic Device Plugin
keywords:
  - generic-device-plugin
  - device
  - plugin
sources:
  - https://github.com/squat/generic-device-plugin
  - https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
maintainers:
  - name: alexlebens
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 4.4.0
appVersion: 0.15.0
