{{- if .Values.secret.externalSecret.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "secret.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secret.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secret.externalSecret.store.name | required "External Secret store name is required" }}
  data:
    - secretKey: {{ include "secret.key" . }}
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ include "secret.path" . }}
        metadataPolicy: None
        property: {{ .Values.secret.externalSecret.store.property | required "External Secret store property is required" }}

{{- end }}
